server:
  port: :8081
  read_timeout_seconds: 10
  write_timeout_seconds: 65
  time_zone: "Asia/Jakarta"
  loglevel: INFO
  base_url: http://localhost:8080
  env: test

sarama:
  brokers: [localhost:9092]
  log: true
  certfile: 
  keyfile:
  cafile:
  verifyssl:

consumer:
  version: 2.8.1
  strategy: roundrobin
  oldest: true
  group: whatever
  topics: [my_topic]