server:
  port: :8080
  read_timeout_seconds: 10
  write_timeout_seconds: 65
  time_zone: "Asia/Jakarta"
  loglevel: INFO
  base_url: http://localhost:8080
  env: test

sarama:
	brokers: [http://localhost:9092]
	log: true
	certfile: 
	keyfile:
	cafile:
	verifyssl:
	topic: test1
  kafka_version: 2.8.1